#Workflow Name
name: Frontend CI

# Triggers for the Workflow
on:

# Automatic Pull Requests on the Main branch
pull_request:
  branches:
    - main
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

# Jobs defined in the workflow
jobs:
  Lint:

    runs-on: ubuntu-latest

    steps:
      - name: lint
      # Run the linter.
      - run: npm run lint

  Test:

    runs-on: ubuntu-latest

    steps:
      - name: test
      # Run the Tests.
      - run: npm test

  Build:

    runs-on: ubuntu-latest

    steps:
      - name: test
      # Run the Tests.
       needs: [Lint ] && [ Test ]
      - run: npm test

