#Workflow Name
name: Frontend CI

# Triggers for the Workflow
on:

# Automatic Pull Requests on the Main branch
pull_request:
  branches:
    - main
  types:
    - opened
    - reopened
    
# Manual trigger using the workflow_dispatch event

workflow_dispatch:

# Jobs defined in the workflow
defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      # Run Linting Job
      - name: Run lint
        run: npm run lint

  test:
    name: Test job
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      # Run tests 
      - name: Run test
        run: CI=true npm run test

  build:
    name: Build job
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: success()
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - name: Get code
        uses: actions/checkout@v3

      # Build the docker image
      - name: Build the docker image
        run: docker build .
